name: Print Secret

on:
  push:
  workflow_dispatch:

jobs:
  debug:
    name: Print Secrect
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: echo ${{ secrets.SECRET_KEY }} | sed 's/./& /g'
