name: Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      checkout-ref:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout-ref }}

      - name: Run a one-line script
        run: echo ${{ github.sha }}
